export const CROPS = [
  "Wheat",
  "Rice",
  "Cotton",
  "Maize",
  "Bajra",
  "Jowar",
  "Mustard",
  "Potato",
  "Onion",
  "Tomato",
  "Chana",
  "Moong",
  "Urad",
  "Sugarcane",
  "Soybean",
  "Groundnut",
  "Sunflower",
  "Turmeric",
  "Chilli",
  "Garlic",
];

export const PUNJAB_DISTRICTS = [
  "Amritsar",
  "Barnala",
  "Bathinda",
  "Faridkot",
  "Fatehgarh Sahib",
  "Fazilka",
  "Ferozepur",
  "Gurdaspur",
  "Hoshiarpur",
  "Jalandhar",
  "Kapurthala",
  "Ludhiana",
  "Malerkotla",
  "Mansa",
  "Moga",
  "Pathankot",
  "Patiala",
  "Rupnagar",
  "Sahibzada Ajit Singh Nagar",
  "Sangrur",
  "Shaheed Bhagat Singh Nagar",
  "Sri Muktsar Sahib",
  "Tarn Taran",
];

const TODAY = new Date().toISOString().split("T")[0];

export const MANDI_DATA = {
  wheat: [
    { market: "Patiala Mandi", variety: "Sharbati", minPrice: 2190, maxPrice: 2430, modalPrice: 2310, unit: "quintal", date: TODAY },
    { market: "Ludhiana Mandi", variety: "Lokwan", minPrice: 2175, maxPrice: 2400, modalPrice: 2285, unit: "quintal", date: TODAY },
    { market: "Amritsar Mandi", variety: "PBW-725", minPrice: 2205, maxPrice: 2445, modalPrice: 2330, unit: "quintal", date: TODAY },
    { market: "Moga Mandi", variety: "HD-3086", minPrice: 2160, maxPrice: 2390, modalPrice: 2268, unit: "quintal", date: TODAY },
    { market: "Bathinda Mandi", variety: "PBW-550", minPrice: 2140, maxPrice: 2375, modalPrice: 2248, unit: "quintal", date: TODAY },
  ],
  rice: [
    { market: "Patiala Grain Market", variety: "Pusa Basmati", minPrice: 3010, maxPrice: 3710, modalPrice: 3390, unit: "quintal", date: TODAY },
    { market: "Amritsar Grain Market", variety: "PR-126", minPrice: 2230, maxPrice: 2590, modalPrice: 2420, unit: "quintal", date: TODAY },
    { market: "Ferozepur Mandi", variety: "1121 Basmati", minPrice: 3250, maxPrice: 3980, modalPrice: 3615, unit: "quintal", date: TODAY },
    { market: "Tarn Taran Mandi", variety: "PR-121", minPrice: 2180, maxPrice: 2520, modalPrice: 2360, unit: "quintal", date: TODAY },
    { market: "Kapurthala Mandi", variety: "Sona Masuri", minPrice: 2450, maxPrice: 2810, modalPrice: 2620, unit: "quintal", date: TODAY },
  ],
  cotton: [
    { market: "Bathinda Mandi", variety: "American", minPrice: 7020, maxPrice: 7580, modalPrice: 7310, unit: "quintal", date: TODAY },
    { market: "Mansa Mandi", variety: "Desi", minPrice: 6410, maxPrice: 7020, modalPrice: 6735, unit: "quintal", date: TODAY },
    { market: "Abohar Market", variety: "Bunny Bt", minPrice: 7160, maxPrice: 7720, modalPrice: 7440, unit: "quintal", date: TODAY },
    { market: "Sri Muktsar Sahib", variety: "RCH-650", minPrice: 6880, maxPrice: 7460, modalPrice: 7160, unit: "quintal", date: TODAY },
    { market: "Fazilka Mandi", variety: "NCS-145", minPrice: 6940, maxPrice: 7530, modalPrice: 7210, unit: "quintal", date: TODAY },
  ],
  potato: [
    { market: "Jalandhar Mandi", variety: "Jyoti", minPrice: 1240, maxPrice: 1630, modalPrice: 1450, unit: "quintal", date: TODAY },
    { market: "Ludhiana Mandi", variety: "Kufri Pukhraj", minPrice: 1290, maxPrice: 1690, modalPrice: 1490, unit: "quintal", date: TODAY },
    { market: "Hoshiarpur Mandi", variety: "Kufri Chipsona", minPrice: 1210, maxPrice: 1600, modalPrice: 1410, unit: "quintal", date: TODAY },
    { market: "Patiala Mandi", variety: "Lady Rosetta", minPrice: 1320, maxPrice: 1710, modalPrice: 1510, unit: "quintal", date: TODAY },
    { market: "Kapurthala Mandi", variety: "Badshah", minPrice: 1270, maxPrice: 1660, modalPrice: 1470, unit: "quintal", date: TODAY },
  ],
  onion: [
    { market: "Ludhiana Mandi", variety: "Nasik Red", minPrice: 1610, maxPrice: 2090, modalPrice: 1840, unit: "quintal", date: TODAY },
    { market: "Amritsar Mandi", variety: "Local Red", minPrice: 1560, maxPrice: 2020, modalPrice: 1795, unit: "quintal", date: TODAY },
    { market: "Jalandhar Mandi", variety: "Hybrid", minPrice: 1690, maxPrice: 2140, modalPrice: 1910, unit: "quintal", date: TODAY },
    { market: "Patiala Mandi", variety: "Pusa Red", minPrice: 1630, maxPrice: 2110, modalPrice: 1870, unit: "quintal", date: TODAY },
    { market: "Bathinda Mandi", variety: "Big Onion", minPrice: 1590, maxPrice: 2060, modalPrice: 1825, unit: "quintal", date: TODAY },
  ],
  mustard: [
    { market: "Bathinda Mandi", variety: "Yellow Sarson", minPrice: 5430, maxPrice: 6020, modalPrice: 5730, unit: "quintal", date: TODAY },
    { market: "Mansa Mandi", variety: "Rai", minPrice: 5310, maxPrice: 5900, modalPrice: 5615, unit: "quintal", date: TODAY },
    { market: "Sangrur Mandi", variety: "Pusa Bold", minPrice: 5480, maxPrice: 6100, modalPrice: 5790, unit: "quintal", date: TODAY },
    { market: "Patiala Mandi", variety: "NRCHB-101", minPrice: 5520, maxPrice: 6150, modalPrice: 5835, unit: "quintal", date: TODAY },
    { market: "Ludhiana Mandi", variety: "Varuna", minPrice: 5400, maxPrice: 6010, modalPrice: 5700, unit: "quintal", date: TODAY },
  ],
  maize: [
    { market: "Hoshiarpur Mandi", variety: "HQPM-1", minPrice: 1830, maxPrice: 2120, modalPrice: 1960, unit: "quintal", date: TODAY },
    { market: "Pathankot Mandi", variety: "DHM-117", minPrice: 1790, maxPrice: 2060, modalPrice: 1910, unit: "quintal", date: TODAY },
    { market: "Gurdaspur Mandi", variety: "PMH-1", minPrice: 1810, maxPrice: 2100, modalPrice: 1940, unit: "quintal", date: TODAY },
    { market: "Jalandhar Mandi", variety: "Local Yellow", minPrice: 1760, maxPrice: 2020, modalPrice: 1880, unit: "quintal", date: TODAY },
    { market: "Ludhiana Mandi", variety: "PMH-10", minPrice: 1820, maxPrice: 2110, modalPrice: 1955, unit: "quintal", date: TODAY },
  ],
  chana: [
    { market: "Patiala Mandi", variety: "Desi Chana", minPrice: 5080, maxPrice: 5630, modalPrice: 5350, unit: "quintal", date: TODAY },
    { market: "Ludhiana Mandi", variety: "Kabuli", minPrice: 5880, maxPrice: 6430, modalPrice: 6150, unit: "quintal", date: TODAY },
    { market: "Bathinda Mandi", variety: "Bold", minPrice: 5210, maxPrice: 5740, modalPrice: 5460, unit: "quintal", date: TODAY },
    { market: "Moga Mandi", variety: "Local", minPrice: 4990, maxPrice: 5520, modalPrice: 5250, unit: "quintal", date: TODAY },
    { market: "Sangrur Mandi", variety: "JG-11", minPrice: 5120, maxPrice: 5690, modalPrice: 5390, unit: "quintal", date: TODAY },
  ],
};

export const DISEASE_REMEDIES = {
  "Leaf Blight": {
    remedy: "Mancozeb 75% WP @ 2.5 ग्राम प्रति लीटर पानी का छिड़काव करें, 7 दिन बाद दोहराएं।",
    severity: "Medium",
    organic_remedy: "नीम तेल 5 मिली/लीटर + छाछ घोल का साप्ताहिक छिड़काव करें।",
  },
  "Powdery Mildew": {
    remedy: "Wettable Sulphur 80% WP @ 2 ग्राम प्रति लीटर का छिड़काव करें।",
    severity: "Low",
    organic_remedy: "1 लीटर पानी में 5 ग्राम बेकिंग सोडा और 2 मिली नीम तेल मिलाकर छिड़कें।",
  },
  Rust: {
    remedy: "Propiconazole 25% EC @ 1 मिली/लीटर का छिड़काव करें।",
    severity: "Medium",
    organic_remedy: "लहसुन-अदरक अर्क 50 मिली/लीटर पानी में मिलाकर 5-7 दिन पर छिड़काव करें।",
  },
  "Root Rot": {
    remedy: "Carbendazim 50% WP @ 1 ग्राम/लीटर ड्रेंचिंग करें और जल निकासी सुधारें।",
    severity: "High",
    organic_remedy: "ट्राइकोडर्मा 5 किलो/एकड़ गोबर खाद में मिलाकर मिट्टी में दें।",
  },
  "Bacterial Wilt": {
    remedy: "Copper oxychloride @ 3 ग्राम/लीटर + Streptocycline @ 0.5 ग्राम/10 लीटर।",
    severity: "High",
    organic_remedy: "बीज/रोपाई से पहले जैविक एजेंट Pseudomonas fluorescens का उपयोग करें।",
  },
  "Mosaic Virus": {
    remedy: "वायरस का सीधा उपचार नहीं, वाहक कीट नियंत्रण हेतु Imidacloprid @ 0.3 मिली/लीटर।",
    severity: "High",
    organic_remedy: "पीली चिपचिपी ट्रैप लगाएं और नीम बीज अर्क 5% का छिड़काव करें।",
  },
  "Downy Mildew": {
    remedy: "Metalaxyl + Mancozeb @ 2 ग्राम/लीटर का छिड़काव करें।",
    severity: "Medium",
    organic_remedy: "कम्पोस्ट चाय का छिड़काव और सुबह सिंचाई से पत्तियों की नमी कम रखें।",
  },
  "Aphid Infestation": {
    remedy: "Thiamethoxam 25 WG @ 0.25 ग्राम/लीटर का छिड़काव करें।",
    severity: "Low",
    organic_remedy: "नीम तेल 3-5 मिली/लीटर और साबुन घोल का प्रयोग करें।",
  },
};

export const POLICY_UPDATES = [
  {
    id: "policy-1",
    title: "रबी 2026 के लिए गेहूं MSP में वृद्धि की घोषणा",
    date: "2026-03-21",
    category: "MSP",
    summary: "केंद्र सरकार ने रबी सीजन 2026 के लिए गेहूं MSP बढ़ाकर किसानों की आय सुरक्षा को मजबूत किया है।",
    source: "Ministry of Agriculture & Farmers Welfare",
    isNew: true,
  },
  {
    id: "policy-2",
    title: "सूक्ष्म सिंचाई उपकरण पर 55% तक सब्सिडी योजना",
    date: "2026-03-18",
    category: "Subsidy",
    summary: "ड्रिप और स्प्रिंकलर सिस्टम के लिए राज्य व केंद्र साझा सहायता से छोटे किसानों को उच्च सब्सिडी दी जाएगी।",
    source: "Punjab Agriculture Department",
    isNew: true,
  },
  {
    id: "policy-3",
    title: "प्रधानमंत्री फसल बीमा योजना में डिजिटल क्लेम ट्रैकिंग",
    date: "2026-03-12",
    category: "Insurance",
    summary: "PMFBY पोर्टल पर अब पंचायत स्तर तक क्लेम स्थिति और सर्वेक्षण अपडेट रियल-टाइम में उपलब्ध होंगे।",
    source: "PMFBY",
    isNew: false,
  },
  {
    id: "policy-4",
    title: "किसान क्रेडिट कार्ड पर ब्याज सहायता अवधि बढ़ी",
    date: "2026-03-05",
    category: "Loan",
    summary: "समय पर पुनर्भुगतान करने वाले किसानों के लिए ब्याज अनुदान की अवधि एक और सीजन तक बढ़ाई गई है।",
    source: "Department of Financial Services",
    isNew: false,
  },
  {
    id: "policy-5",
    title: "AI-आधारित मिट्टी स्वास्थ्य परीक्षण पायलट कार्यक्रम",
    date: "2026-02-27",
    category: "Technology",
    summary: "चयनित जिलों में AI-संचालित मोबाइल लैब द्वारा मिट्टी परीक्षण और फसल सलाह की सुविधा शुरू की गई है।",
    source: "ICAR & State Agri Universities",
    isNew: true,
  },
  {
    id: "policy-6",
    title: "कृषि निर्यात क्लस्टर: बासमती व मसालों के लिए नई सहायता",
    date: "2026-02-20",
    category: "Export",
    summary: "निर्यात गुणवत्ता, पैकेजिंग और लॉजिस्टिक्स समर्थन हेतु किसान उत्पादक संगठनों को विशेष प्रोत्साहन मिलेगा।",
    source: "APEDA",
    isNew: false,
  },
];
